package:
  name: rdock
  version: "2022.0"

source:
  path: ..

build:
  number: 0
  script:
    - "mkdir -p $PREFIX/bin"
    - "mkdir -p $PREFIX/lib"
    - "cp bin/* $PREFIX/bin/"
    - "cp lib/* $PREFIX/lib/"
    - "chmod u+x $PREFIX/bin/*"

about:
  license: open-source
