package:
  name: rdock
  version: "2022.0"

source:
  path: ..

build:
  number: "1"

requirements:
  build:
    - perl
    - python
  run:
    - libgcc
    - numpy
    - perl

test:
  commands:
    - rbcavity --help
    - rbdock --help
    - sdrmsd --help
    - sdsort -h

about:
  home: http://rdock.sourceforge.net/
  license: LGPLv3
  license_file: license.txt
  summary:
    A Fast, Versatile and Open Source Program for Docking Ligands to Proteins
    and Nucleic Acids
