name: Build package and publish

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]

    defaults: # Needed for conda
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          uses-mamba: true
          miniforge-variant: Mambaforge
          channels: conda-forge,defaults

      - name: Install yum deps
        run: sudo apt-get install -y gcc g++ make libpopt-dev libcppunit-dev

      # - name: Build rDock binaries
      #   working-directory: ./build
      #   run: |
      #     chmod a+x p4utils.pl
      #     make linux-g++-64

      # - name: Test rDock binaries
      #   working-directory: ./build
      #   run: make test

      - name: Build rDock package
        shell: bash -l {0}
        run: |
          conda install anaconda-client conda-build conda-verify
          conda build conda-package/ --output-folder ./pkg/ --no-include-recipe --no-anaconda-upload -c conda-forge

      - name: Test package
        run: |
          conda install -q -y ./pkg/linux-64/rdock-*.tar.bz2
          conda install -q -y pytest
          pytest ./tests/

      - name: Upload to conda
        shell: bash -l {0}
        run: |
          anaconda -t ${{ secrets.ANACONDA_TOKEN_BASIC }} upload -u acellera ./pkg/*/rdock-*.tar.bz2
