name: Build package and publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]
        container: ["quay.io/pypa/manylinux_2_28_x86_64"]

    defaults: # Needed for conda
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          uses-mamba: true
          miniforge-variant: Mambaforge
          channels: conda-forge,defaults
          activate-environment: ../my-env

      - name: Install yum deps
        run: |
          yum groupinstall -y "Development Tools"
          yum install -y popt-devel cppunit-devel

      - name: Build rDock package
        shell: bash -l {0}
        run: |
          git config --global --add safe.directory '*'
          conda install anaconda-client conda-build conda-verify
          conda build conda-package/ --output-folder ./pkg/ --no-include-recipe --no-anaconda-upload -c conda-forge

      - name: Test package
        run: |
          conda install -q -y ./pkg/linux-64/rdock-*.tar.bz2
          conda install -q -y pytest
          pytest ./tests/

      - name: Upload to conda
        shell: bash -l {0}
        run: |
          anaconda -t ${{ secrets.ANACONDA_TOKEN_BASIC }} upload -u acellera ./pkg/*/rdock-*.tar.bz2
